#!/bin/bash
#==============================================================================
#
# Munin plugin to monitor NVIDIA Tesla M2090 GPU statistics
# via nvidia-smi (340.29)
#
#==============================================================================
NVIDIA_SMI="/usr/bin/nvidia-smi"
if [[ ! -x "$NVIDIA_SMI" ]]; then
    echo "${NVIDIA_SMI} is not found or not executable. Exit"
    exit 1
fi

config() {
    BUFFER=$(${NVIDIA_SMI} -L)
    GPUS=($BUFFER)
    NGPU=$(echo -e "$BUFFER" | wc -l)
    echo "multigraph nvidia_smi_temperature"
    echo "graph_title NVIDIA GPU Temperature"
    echo "graph_vlabel temperature (C)"
    echo "graph_category gpu"
    for GPU in $(seq 0 $(expr $NGPU - 1)); do
        echo "GPU${GPU}.label ${GPUS[$GPU]}"
        echo "GPU${GPU}.warning 80"
        echo "GPU${GPU}.critical 100"
    done

    echo "multigraph nvidia_smi_gpu_utilization"
    echo "graph_title NVIDIA GPU utilization"
    echo "graph_vlabel utilization (%)"
    echo "graph_category gpu"
    for GPU in $(seq 0 $(expr $NGPU - 1)); do
        echo "GPU${GPU}.label ${GPUS[$GPU]}"
    done

    echo "multigraph nvidia_smi_memory_utilization"
    echo "graph_title NVIDIA Memory utilization"
    echo "graph_vlabel utilization (%)"
    echo "graph_category gpu"
    for GPU in $(seq 0 $(expr $NGPU - 1)); do
        echo "GPU${GPU}.label ${GPUS[$GPU]}"
    done
    exit 0
}

run() {
    BUFFER="$(${NVIDIA_SMI} -q)"
    NGPU=$(echo -e "$BUFFER" | \
        egrep '^Attached GPUs' | \
        sed -e 's/.*: //' )
    TEMP=($(echo -e "$BUFFER" | \
        egrep -A 1 '^\W+Temperature$' | \
        egrep '[[:digit:]]+ C' | \
        sed -e 's/.*: //' -e 's/C$//'))
    UGPU=($(echo -e "$BUFFER" | \
        egrep -A 2 '^\W+Utilization$' | \
        egrep 'Gpu\W*: [[:digit:]]+ %' | \
        sed -e 's/.*: //' -e 's/%$//'))
    UMEM=($(echo -e "$BUFFER" | \
        egrep -A 2 '^\s+Utilization$' | \
        egrep 'Memory\W*: [[:digit:]]+ %' | \
        sed -e 's/.*: //' -e 's/%$//'))

    echo "multigraph nvidia_smi_temperature"
    for GPU in $(seq 0 $(expr $NGPU - 1)); do
        echo "GPU${GPU}.value ${TEMP[${GPU}]}"
    done

    echo "multigraph nvidia_smi_gpu_utilization"
    for GPU in $(seq 0 $(expr $NGPU - 1)); do
        echo "GPU${GPU}.value ${UGPU[${GPU}]}"
    done

    echo "multigraph nvidia_smi_memory_utilization"
    for GPU in $(seq 0 $(expr $NGPU - 1)); do
        echo "GPU${GPU}.value ${UMEM[${GPU}]}"
    done
    exit 0
}


case $1 in
    config)
        config;;
    *)
        run;;
esac
